-- Deploy tenisu:initSchema to pg

BEGIN;

-- CREATE TABLE "players_one" (
--   id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
--   firstname VARCHAR(255) NOT NULL,
--   lastname VARCHAR(255) NOT NULL,
--   shortname VARCHAR(20) NOT NULL,
--   sex VARCHAR(1) NOT NULL,
--   country JSONB NOT NULL,
--   picture VARCHAR(255) NOT NULL,
--   data JSONB NOT NULL
-- );

CREATE TABLE "players" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  shortname VARCHAR(20) NOT NULL,
  sex VARCHAR(1) NOT NULL,
  picture VARCHAR(255) NOT NULL
);

CREATE TABLE "country" (
   id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   picture VARCHAR(255) NOT NULL,
   code VARCHAR(3) NOT NULL,
   players_id INT NOT NULL,
   CONSTRAINT "fk_players_id" FOREIGN KEY ("players_id") REFERENCES "players" ("id") ON DELETE CASCADE
);

CREATE TABLE "data" (
   id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
   rank INT NOT NULL,
   points INT NOT NULL,
   weight NUMERIC(10,4) NOT NULL,
   height NUMERIC(5,2) NOT NULL,
   age INT NOT NULL,
   last INTEGER[] NOT NULL,
   players_id INT NOT NULL,
   CONSTRAINT "fk_players_id" FOREIGN KEY ("players_id") REFERENCES "players" ("id") ON DELETE CASCADE
);

COMMIT;
