-- Deploy tenisu:initSchema to pg

BEGIN;

CREATE TABLE "players" (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  firstname VARCHAR(255) NOT NULL,
  lastname VARCHAR(255) NOT NULL,
  shortname VARCHAR(20) NOT NULL,
  sex VARCHAR(1) NOT NULL,
  country JSONB NOT NULL,
  picture VARCHAR(255) NOT NULL,
  data JSONB NOT NULL
);

COMMIT;
